# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions
{{ readFile "../../launchpad-core/helmfiles/templates/avalanche-mainnet.yaml" }}

releases:
  - name: avalanche-archive-trace-mainnet-0
    <<: *launchpad-release-template-avalanche-archive-trace-mainnet
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: proxyd-avalanche-mainnet
    <<: *launchpad-release-template-proxyd-avalanche-mainnet
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: private-ingress-avalanche-mainnet
    <<: *launchpad-release-template-resource-injector
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
